services:
  web:
    image: php:8.3-apache
    container_name: afpagram-apache
    volumes:
      - .:/var/www/html
    ports:
      - "8800:80"
      - "9003:9003"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=app_db
    networks:
      - app-network
    build:
      context: .
      dockerfile: Dockerfile


  db:
    image: mysql:8.0
    container_name: afpagram-db
    restart: always
    environment:
      MYSQL_DATABASE: afpa-gram
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: afpagramphpmyadmin
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network


volumes:
  db_data:


networks:
  app-network: